### ISSUE TITLE
No peers and source available 

### ISSUE THREAD

**Issue by Heijn** [mooncoincore/wallet#11]
Yesterday I have downloaded the Mooncoin Wallet, but it took ages for syncing. So I searched and found the cryptochainer.com. Now he says that I have only twee weeks left for syncing, but he doesn't have a source available and there are no peers. So he isn't syncing. What to do?

**Comment by baziez** [comment]
try to add:
addnode=213.169.33.11:44664
addnode=5.45.105.66
addnode=80.101.227.103
addnode=45.32.217.146
addnode=107.150.52.122
addnode=18.218.28.213
addnode=91.235.254.37
addnode=99.162.146.53
addnode=173.255.194.32
addnode=150.147.119.6:44664
addnode=121.135.115.249:44664
addnode=192.99.6.207:44664


in your mooncoin.conf file at:
C:\Users\Happyuser\AppData\Roaming\Mooncoin

**Comment by IlyaPolanskis** [comment]
If you don't have mooncoin.conf file inside (like in my case) - just create it and add inside all lines from baziez comment.

> addnode=213.169.33.11:44664
addnode=5.45.105.66
addnode=80.101.227.103
addnode=45.32.217.146
addnode=107.150.52.122
addnode=18.218.28.213
addnode=91.235.254.37
addnode=99.162.146.53
addnode=173.255.194.32
addnode=150.147.119.6:44664
addnode=121.135.115.249:44664
addnode=192.99.6.207:44664

**Comment by mebagger** [comment]
edit the  mooncoin.conf  and add these entries, as they should always be up to date:
seednode=dnsseed01.moonypool.com
seednode=dnsseed02.moonypool.com
seednode=dnsseed03.moonypool.com

**Comment by mooncoincore** [comment]
fixed in #15
