### ISSUE TITLE
how to redeem mooncoin on mooncoincore wallet

### ISSUE THREAD

**Issue by zangsign** [mooncoincore/wallet#12]
i downloaded mooncoincore wallet for windows 64 bit and purchased mooncoin on bleutreade.com and withdrew the tokens to an address in my wallet.  nothing ever arrived.   it is showing that they were successfully withdrawn from bleutrade to my address, but not showing up in my wallet.  i have tried restarting the computer several times.  i looked up the txid and it shows the blockchain transaction but says the coins are not redeemed.  i have no clue how to redeem the coins.  i hate these little wallets.  there are always issues like this.  i already lost .5 million doge coins.  i would appreciate if someone could offer some advice to resolve this issue.  thanks

**Comment by mebagger** [comment]
This is an issue for bleutreade.com support.
