### ISSUE TITLE
Cannot launch wallet

### ISSUE THREAD

**Issue by etothepi16** [mooncoincore/wallet#2]
I get the following error every time I try to launch the latest release of the wallet (0.13.9-segwit):
> MinGW Runtime Assertion
> Assertion failed!
> Program: C:\Program Files\MooncoinWallet\mooncoinWallet.exe
> File: main.cpp, Line 2591
>
> Expression: hashPrevBlock == view.GetBestBlock()

**Comment by mooncoincore** [comment]
Please erase the old database in mooncoin folder. keep only your wallet.dat and peers.dat.

**Comment by etothepi16** [comment]
Thank you. That worked!
