### ISSUE TITLE
mooncoincore/wallet

### ISSUE THREAD

**Issue by 727guy** [mooncoincore/wallet#3]
the windows readme is simple enough....extract files and run mooncoin-qt.exe, only that file isnt present in any of the  wallet-0.13.9-segwit. Am I missing something really simple? Trying to restore my wallet from 2014...

**Comment by mooncoincore** [comment]
the file named mooncoinWallet.exe

**Comment by 727guy** [comment]
there is no mooncoinWallet.exe in any of the extracted files

**Comment by mooncoincore** [comment]
there is no zip files in release...
just the mooncoinWallet.exe for 32bit and 64bit versions
and 2 setup.exe with miner and without.
The source.zip has no exe inside because is for build.

**Comment by mooncoincore** [comment]
Please check the release tab!
https://github.com/mooncoincore/wallet/releases
you will find..
 mooncoinWallet_i686.exe
mooncoinWallet_Setup.exe
mooncoinWallet_without_miner_Setup.exe
mooncoinWallet_x86-64.exe

**Comment by mooncoincore** [comment]
I assume you found the executables.

**Comment by 727guy** [comment]
yes thank you very much!
