### ISSUE TITLE
"No block source available"

### ISSUE THREAD

**Issue by etothepi16** [mooncoincore/wallet#4]
I get this message every time I open the wallet. I've tried changing network settings and allowing it through my firewall but nothing has worked; I continue to have no connections to the mooncoin network available.

**Comment by mooncoincore** [comment]
Do you have enable proxy server? If yes, please disable it. Settings > Options > Network Tab.

Try to add this nodes in your mooncoin directory in mooncoin.conf 

addnode=103.9.88.57
addnode=104.157.4.179
addnode=115.178.200.47
addnode=172.116.129.173
addnode=172.56.5.235
addnode=174.26.255.13
addnode=176.240.118.58
addnode=178.128.93.177
addnode=178.192.9.127
addnode=180.56.82.182
addnode=187.154.187.154
addnode=188.230.145.127
addnode=189.128.67.118
addnode=192.64.114.237
addnode=192.99.6.207
addnode=2.34.174.67
addnode=210.131.152.174
addnode=212.171.69.239
addnode=5.147.42.220
addnode=5.45.105.66
addnode=5.9.14.199
addnode=61.6.92.20
addnode=73.61.204.73
addnode=76.169.57.92
addnode=77.69.98.9
addnode=82.212.112.224
addnode=84.28.152.243
addnode=85.139.117.184
addnode=86.57.220.62
addnode=88.84.22.93
addnode=89.211.239.69
addnode=91.195.22.50
addnode=93.106.47.135
addnode=95.189.57.224
addnode=98.255.202.19
