### ISSUE TITLE
Compiling - question

### ISSUE THREAD

**Issue by coinflow** [mooncoincore/wallet#5]
Hi Vassilis,

first of all, thanks for the new Mooncoin-wallet.

But I've got a question.
While compiling, the following was displayed:

balloon/balloonpow.c: In function 'balloonpow_hash':
balloon/balloonpow.c:29:25: warning: passing argument 2 of 'hash_state_extract' discards 'const' qualifier from pointer target type
   hash_state_extract(&s,output);
                         ^
In file included from balloon/balloonpow.c:11:0:
balloon/hash_state.h:48:5: note: expected 'uint8_t *' but argument is of type 'const void *'
 int hash_state_extract (const struct hash_state *s, uint8_t out[BLOCK_SIZE]);

I thought the BalloonHash was abandoned altogether, so why does it still occur in the compilation-process?

Thanks and best regards

coinflow

**Comment by mooncoincore** [comment]
Balloon hash is disabled for now at least! I didn't erase it.
